name: "CI setup"
runs:
  using: "composite"
  steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
