// flow-typed signature: 638c36665cc2ca6b5e23c517d8ad7884
// flow-typed version: <<STUB>>/babel-preset-preact_v1.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-preact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-preact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-preact/index' {
  declare module.exports: $Exports<'babel-preset-preact'>;
}
declare module 'babel-preset-preact/index.js' {
  declare module.exports: $Exports<'babel-preset-preact'>;
}
