// flow-typed signature: 122f9e858e308bd3c1450027842ca9ce
// flow-typed version: <<STUB>>/eventemitter3_v3.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eventemitter3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eventemitter3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eventemitter3/umd/eventemitter3.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eventemitter3/index' {
  declare module.exports: $Exports<'eventemitter3'>;
}
declare module 'eventemitter3/index.js' {
  declare module.exports: $Exports<'eventemitter3'>;
}
declare module 'eventemitter3/umd/eventemitter3.min.js' {
  declare module.exports: $Exports<'eventemitter3/umd/eventemitter3.min'>;
}
