// flow-typed signature: 6c013a70dae256112eb1f30cc23cde13
// flow-typed version: <<STUB>>/html-webpack-plugin_vwebpack-contrib/html-webpack-plugin/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-webpack-plugin/examples/appcache/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/appcache/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/appcache/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/appcache/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/appcache/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/appcache/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/build-examples' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/custom-template/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/custom-template/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/custom-template/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/custom-template/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/custom-template/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/custom-template/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/default/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/default/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/default/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/default/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/default/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/default/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/favicon/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/favicon/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/favicon/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/favicon/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/favicon/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/favicon/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/html-loader/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/html-loader/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/html-loader/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/html-loader/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/html-loader/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/html-loader/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/inline/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/inline/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/inline/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/inline/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/inline/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/inline/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/jade-loader/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/jade-loader/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/jade-loader/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/jade-loader/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/jade-loader/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/jade-loader/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript-advanced/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript-advanced/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript-advanced/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript-advanced/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript-advanced/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript-advanced/template' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript-advanced/universial' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript-advanced/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript/dist/webpack-1/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript/dist/webpack-2/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript/dist/webpack-3/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript/dist/webpack-4/bundle' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript/example' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript/template' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript/universial' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/javascript/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/a' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/b' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/c' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/d' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/a' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/b' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/c' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/d' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/e' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/a' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/b' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/c' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/d' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/e' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/a' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/b' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/c' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/d' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/e' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/a' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/b' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/c' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/d' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/e' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/e' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/examples/sort-manually/webpack.config' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/chunksorter' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/compiler' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/errors' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/loader' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/BasicSpec' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/CachingSpec' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/ExampleSpec' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/fixtures/async' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/fixtures/common' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/fixtures/index' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/fixtures/templateParam' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/fixtures/theme' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/spec/fixtures/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-webpack-plugin/examples/appcache/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/appcache/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/appcache/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/appcache/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/appcache/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/appcache/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/appcache/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/appcache/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/appcache/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/appcache/example'>;
}
declare module 'html-webpack-plugin/examples/appcache/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/appcache/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/build-examples.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/build-examples'>;
}
declare module 'html-webpack-plugin/examples/custom-template/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/custom-template/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/custom-template/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/custom-template/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/custom-template/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/custom-template/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/custom-template/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/custom-template/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/custom-template/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/custom-template/example'>;
}
declare module 'html-webpack-plugin/examples/custom-template/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/custom-template/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/default/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/default/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/default/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/default/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/default/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/default/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/default/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/default/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/default/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/default/example'>;
}
declare module 'html-webpack-plugin/examples/default/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/default/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/favicon/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/favicon/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/favicon/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/favicon/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/favicon/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/favicon/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/favicon/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/favicon/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/favicon/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/favicon/example'>;
}
declare module 'html-webpack-plugin/examples/favicon/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/favicon/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/html-loader/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/html-loader/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/html-loader/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/html-loader/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/html-loader/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/html-loader/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/html-loader/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/html-loader/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/html-loader/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/html-loader/example'>;
}
declare module 'html-webpack-plugin/examples/html-loader/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/html-loader/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/inline/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/inline/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/inline/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/inline/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/inline/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/inline/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/inline/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/inline/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/inline/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/inline/example'>;
}
declare module 'html-webpack-plugin/examples/inline/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/inline/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/jade-loader/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/jade-loader/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/jade-loader/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/jade-loader/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/jade-loader/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/jade-loader/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/jade-loader/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/jade-loader/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/jade-loader/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/jade-loader/example'>;
}
declare module 'html-webpack-plugin/examples/jade-loader/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/jade-loader/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/javascript-advanced/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript-advanced/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/javascript-advanced/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript-advanced/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/javascript-advanced/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript-advanced/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/javascript-advanced/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript-advanced/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/javascript-advanced/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript-advanced/example'>;
}
declare module 'html-webpack-plugin/examples/javascript-advanced/template.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript-advanced/template'>;
}
declare module 'html-webpack-plugin/examples/javascript-advanced/universial.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript-advanced/universial'>;
}
declare module 'html-webpack-plugin/examples/javascript-advanced/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript-advanced/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/javascript/dist/webpack-1/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript/dist/webpack-1/bundle'>;
}
declare module 'html-webpack-plugin/examples/javascript/dist/webpack-2/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript/dist/webpack-2/bundle'>;
}
declare module 'html-webpack-plugin/examples/javascript/dist/webpack-3/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript/dist/webpack-3/bundle'>;
}
declare module 'html-webpack-plugin/examples/javascript/dist/webpack-4/bundle.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript/dist/webpack-4/bundle'>;
}
declare module 'html-webpack-plugin/examples/javascript/example.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript/example'>;
}
declare module 'html-webpack-plugin/examples/javascript/template.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript/template'>;
}
declare module 'html-webpack-plugin/examples/javascript/universial.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript/universial'>;
}
declare module 'html-webpack-plugin/examples/javascript/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/javascript/webpack.config'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/a.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/a'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/b.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/b'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/c.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/c'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/d.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/d'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/a.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-1/a'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/b.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-1/b'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/c.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-1/c'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/d.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-1/d'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-1/e.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-1/e'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/a.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-2/a'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/b.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-2/b'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/c.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-2/c'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/d.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-2/d'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-2/e.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-2/e'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/a.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-3/a'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/b.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-3/b'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/c.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-3/c'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/d.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-3/d'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-3/e.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-3/e'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/a.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-4/a'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/b.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-4/b'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/c.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-4/c'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/d.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-4/d'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/dist/webpack-4/e.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/dist/webpack-4/e'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/e.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/e'>;
}
declare module 'html-webpack-plugin/examples/sort-manually/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-plugin/examples/sort-manually/webpack.config'>;
}
declare module 'html-webpack-plugin/index' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/lib/chunksorter.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/chunksorter'>;
}
declare module 'html-webpack-plugin/lib/compiler.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/compiler'>;
}
declare module 'html-webpack-plugin/lib/errors.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/errors'>;
}
declare module 'html-webpack-plugin/lib/loader.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/loader'>;
}
declare module 'html-webpack-plugin/spec/BasicSpec.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/BasicSpec'>;
}
declare module 'html-webpack-plugin/spec/CachingSpec.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/CachingSpec'>;
}
declare module 'html-webpack-plugin/spec/ExampleSpec.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/ExampleSpec'>;
}
declare module 'html-webpack-plugin/spec/fixtures/async.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/fixtures/async'>;
}
declare module 'html-webpack-plugin/spec/fixtures/common.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/fixtures/common'>;
}
declare module 'html-webpack-plugin/spec/fixtures/index.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/fixtures/index'>;
}
declare module 'html-webpack-plugin/spec/fixtures/templateParam.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/fixtures/templateParam'>;
}
declare module 'html-webpack-plugin/spec/fixtures/theme.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/fixtures/theme'>;
}
declare module 'html-webpack-plugin/spec/fixtures/util.js' {
  declare module.exports: $Exports<'html-webpack-plugin/spec/fixtures/util'>;
}
