// flow-typed signature: 464a7f18790c95f35499398b2f8f94b1
// flow-typed version: <<STUB>>/localStorage_v1.0.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'localStorage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'localStorage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'localStorage/lib/localStorage' {
  declare module.exports: any;
}

declare module 'localStorage/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'localStorage/lib/localStorage.js' {
  declare module.exports: $Exports<'localStorage/lib/localStorage'>;
}
declare module 'localStorage/tests/test.js' {
  declare module.exports: $Exports<'localStorage/tests/test'>;
}
