// flow-typed signature: 7d9aee064d796cc86555bf389b86fece
// flow-typed version: <<STUB>>/preact-test-utils_v0.1.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-test-utils/lib/events' {
  declare module.exports: any;
}

declare module 'preact-test-utils/lib/index' {
  declare module.exports: any;
}

declare module 'preact-test-utils/src/events' {
  declare module.exports: any;
}

declare module 'preact-test-utils/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-test-utils/lib/events.js' {
  declare module.exports: $Exports<'preact-test-utils/lib/events'>;
}
declare module 'preact-test-utils/lib/index.js' {
  declare module.exports: $Exports<'preact-test-utils/lib/index'>;
}
declare module 'preact-test-utils/src/events.js' {
  declare module.exports: $Exports<'preact-test-utils/src/events'>;
}
declare module 'preact-test-utils/src/index.js' {
  declare module.exports: $Exports<'preact-test-utils/src/index'>;
}
