// flow-typed signature: 5ad3548a0969a42f3344a264ed156c87
// flow-typed version: <<STUB>>/preact-jsx-chai_v2.2.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-jsx-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-jsx-chai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-jsx-chai/dist/index' {
  declare module.exports: any;
}

declare module 'preact-jsx-chai/src/index' {
  declare module.exports: any;
}

declare module 'preact-jsx-chai/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-jsx-chai/dist/index.js' {
  declare module.exports: $Exports<'preact-jsx-chai/dist/index'>;
}
declare module 'preact-jsx-chai/src/index.js' {
  declare module.exports: $Exports<'preact-jsx-chai/src/index'>;
}
declare module 'preact-jsx-chai/test/index.js' {
  declare module.exports: $Exports<'preact-jsx-chai/test/index'>;
}
