// flow-typed signature: 13a2dd1555fd358b6168e1cb4cd138b9
// flow-typed version: <<STUB>>/spin.js_v3.1.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spin.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spin.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spin.js/Gruntfile' {
  declare module.exports: any;
}

declare module 'spin.js/spin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spin.js/Gruntfile.js' {
  declare module.exports: $Exports<'spin.js/Gruntfile'>;
}
declare module 'spin.js/spin.js' {
  declare module.exports: $Exports<'spin.js/spin'>;
}
