// flow-typed signature: 3a18762173688726f997bc10976d248f
// flow-typed version: <<STUB>>/svg-pan-zoom_v3.5.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-pan-zoom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-pan-zoom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-pan-zoom/demo/hammer' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/demo/jquery.min' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/demo/require-main' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/demo/thumbnailViewer' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/dist/svg-pan-zoom' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/dist/svg-pan-zoom.min' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/gulpfile' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/server' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/src/browserify' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/src/control-icons' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/src/shadow-viewport' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/src/stand-alone' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/src/svg-pan-zoom' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/src/svg-utilities' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/src/uniwheel' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/src/utilities' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/tests/assets/blanket' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/tests/assets/jquery.min' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/tests/assets/qunit' {
  declare module.exports: any;
}

declare module 'svg-pan-zoom/tests/test_api' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-pan-zoom/demo/hammer.js' {
  declare module.exports: $Exports<'svg-pan-zoom/demo/hammer'>;
}
declare module 'svg-pan-zoom/demo/jquery.min.js' {
  declare module.exports: $Exports<'svg-pan-zoom/demo/jquery.min'>;
}
declare module 'svg-pan-zoom/demo/require-main.js' {
  declare module.exports: $Exports<'svg-pan-zoom/demo/require-main'>;
}
declare module 'svg-pan-zoom/demo/thumbnailViewer.js' {
  declare module.exports: $Exports<'svg-pan-zoom/demo/thumbnailViewer'>;
}
declare module 'svg-pan-zoom/dist/svg-pan-zoom.js' {
  declare module.exports: $Exports<'svg-pan-zoom/dist/svg-pan-zoom'>;
}
declare module 'svg-pan-zoom/dist/svg-pan-zoom.min.js' {
  declare module.exports: $Exports<'svg-pan-zoom/dist/svg-pan-zoom.min'>;
}
declare module 'svg-pan-zoom/gulpfile.js' {
  declare module.exports: $Exports<'svg-pan-zoom/gulpfile'>;
}
declare module 'svg-pan-zoom/server.js' {
  declare module.exports: $Exports<'svg-pan-zoom/server'>;
}
declare module 'svg-pan-zoom/src/browserify.js' {
  declare module.exports: $Exports<'svg-pan-zoom/src/browserify'>;
}
declare module 'svg-pan-zoom/src/control-icons.js' {
  declare module.exports: $Exports<'svg-pan-zoom/src/control-icons'>;
}
declare module 'svg-pan-zoom/src/shadow-viewport.js' {
  declare module.exports: $Exports<'svg-pan-zoom/src/shadow-viewport'>;
}
declare module 'svg-pan-zoom/src/stand-alone.js' {
  declare module.exports: $Exports<'svg-pan-zoom/src/stand-alone'>;
}
declare module 'svg-pan-zoom/src/svg-pan-zoom.js' {
  declare module.exports: $Exports<'svg-pan-zoom/src/svg-pan-zoom'>;
}
declare module 'svg-pan-zoom/src/svg-utilities.js' {
  declare module.exports: $Exports<'svg-pan-zoom/src/svg-utilities'>;
}
declare module 'svg-pan-zoom/src/uniwheel.js' {
  declare module.exports: $Exports<'svg-pan-zoom/src/uniwheel'>;
}
declare module 'svg-pan-zoom/src/utilities.js' {
  declare module.exports: $Exports<'svg-pan-zoom/src/utilities'>;
}
declare module 'svg-pan-zoom/tests/assets/blanket.js' {
  declare module.exports: $Exports<'svg-pan-zoom/tests/assets/blanket'>;
}
declare module 'svg-pan-zoom/tests/assets/jquery.min.js' {
  declare module.exports: $Exports<'svg-pan-zoom/tests/assets/jquery.min'>;
}
declare module 'svg-pan-zoom/tests/assets/qunit.js' {
  declare module.exports: $Exports<'svg-pan-zoom/tests/assets/qunit'>;
}
declare module 'svg-pan-zoom/tests/test_api.js' {
  declare module.exports: $Exports<'svg-pan-zoom/tests/test_api'>;
}
