name: "CI checks"
runs:
  using: "composite"
  steps:
    - name: Build
      run: pnpm run build
      shell: bash

    - name: Typecheck
      run: pnpm run check-ts
      shell: bash

    - name: Lint
      run: pnpm run lint
      shell: bash

    - name: Test
      run: pnpm run test
      shell: bash
