export default {
  total_entries: 246,
  ticket_groups: [
    {
      id: 457658753,
      url: '/ticket_groups/457658753',
      type: 'event',
      row: 'GA2',
      section: 'JEFFER',
      quantity: 1,
      available_quantity: 1,
      section_id: '',
      ticket_type: 'primary',
      wholesale_price: 20.6,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes:
        'TMX XFER - Electronic Transfer - Mobile Entry Tickets. Must have smart device on hand to enter event. Parking Pass Listing ONLY',
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-04-09T16:19:53Z',
      updated_at: '2018-04-09T16:19:53Z',
      splits: [1],
      ticket_states: { available: 1 },
      ticket_hold_ids: ['NULL'],
      seats: [],
      tickets: [['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 20.6,
      format: 'TM_mobile',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 20,
      ticket_costs: [null],
      ticket_purchase_order_ids: [null],
      freshness: '< 30 mins',
      signature:
        'aU9WU0s5cTVmVERneGt5dk5iYURhYmRUYVN1SEJpNnlSV0YySk56RmNWMD0tLWlDcFVCWUdnMW54RUtGaEdWa0EzaEE9PQ==--9f2638c337b71d98e1ac1b146d0fce262b720c18',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: true
    },
    {
      id: 457658755,
      url: '/ticket_groups/457658755',
      type: 'event',
      row: 'GA2',
      section: 'JEFFER',
      quantity: 1,
      available_quantity: 1,
      section_id: '',
      ticket_type: 'primary',
      wholesale_price: 20.6,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes:
        'TMX XFER - Electronic Transfer - Mobile Entry Tickets. Must have smart device on hand to enter event. Parking Pass Listing ONLY',
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-04-09T16:19:53Z',
      updated_at: '2018-04-09T16:19:53Z',
      splits: [1],
      ticket_states: { available: 1 },
      ticket_hold_ids: ['NULL'],
      seats: [],
      tickets: [['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 20.6,
      format: 'TM_mobile',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 20,
      ticket_costs: [null],
      ticket_purchase_order_ids: [null],
      freshness: '< 30 mins',
      signature:
        'SGM5VVZrcUwxRWR3M3hDZDY3bnU1UHBzSWk1MFhkQXRZdkp4clAvSVM0dz0tLWJKYUpBcFlCQ3lUaThDRXp0UU50VXc9PQ==--a63e06a9a66f5bcfdf5c2ce70a6059f30c7b4aa8',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: true
    },
    {
      id: 449625448,
      url: '/ticket_groups/449625448',
      type: 'event',
      row: '13',
      section: '320',
      quantity: 4,
      available_quantity: 4,
      section_id: 119457,
      ticket_type: 'cheap',
      wholesale_price: 22.65,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: false,
      in_hand_on: '2018-04-18',
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-03-08T18:50:48Z',
      updated_at: '2018-03-26T19:11:16Z',
      splits: [2, 4],
      ticket_states: { available: 4 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 22.65,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 22.44,
      ticket_costs: [null, null, null, null],
      ticket_purchase_order_ids: [null, null, null, null],
      freshness: '< 30 mins',
      signature:
        'SnprSzlXdDl4bEloMW9ab3N6TE40Mi80SkoyRUR0R1FLbHhwRXlRZ2Rqcz0tLWFlZjJPWmJReC8wN21yUnhqMXFKa0E9PQ==--c1f9ae2fa8a1ee7bb5a4a88cfc06624f4385b5d4',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 436051338,
      url: '/ticket_groups/436051338',
      type: 'event',
      row: '12',
      section: '318',
      quantity: 3,
      available_quantity: 3,
      section_id: 119455,
      ticket_type: 'cheap',
      wholesale_price: 23.79,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-01-16T21:35:38Z',
      updated_at: '2018-04-09T15:20:34Z',
      splits: [1, 3],
      ticket_states: { available: 3 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 23.79,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 23.1,
      ticket_costs: [null, null, null],
      ticket_purchase_order_ids: [null, null, null],
      freshness: '< 30 mins',
      signature:
        'c0JMZEZ4Unc3Smx2QThuaWlBUEYxWjV3ZW8vMHlRK2NiSUUxWjZ4UUpDQT0tLU5CMkZPVjhVTGhHTTlqUlBlTnE1c2c9PQ==--ac848020388596bf60f6b9acfb4b7be8c34dd4c7',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 436050796,
      url: '/ticket_groups/436050796',
      type: 'event',
      row: '3',
      section: '301',
      quantity: 2,
      available_quantity: 2,
      section_id: 119462,
      ticket_type: 'cheap',
      wholesale_price: 24.87,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-01-16T21:32:58Z',
      updated_at: '2018-04-08T16:18:34Z',
      splits: [2],
      ticket_states: { available: 2 },
      ticket_hold_ids: ['NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 24.87,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 24.15,
      ticket_costs: [null, null],
      ticket_purchase_order_ids: [null, null],
      freshness: '< 30 mins',
      signature:
        'd2NnWkM0RGczSDl5R0Vqek9iQ3Q3Sk43Sk1ZM2NjTmRSajlXdkExWk5Ddz0tLUNCckFJdm1VUUpBSGNLNEdXVy9weGc9PQ==--930333c2999e535f1a2adfa77647578bca0ff0ff',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 443291881,
      url: '/ticket_groups/443291881',
      type: 'event',
      row: '13',
      section: '320',
      quantity: 3,
      available_quantity: 3,
      section_id: 119457,
      ticket_type: 'cheap',
      wholesale_price: 25.96,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-02-13T15:42:12Z',
      updated_at: '2018-04-09T15:20:40Z',
      splits: [1, 3],
      ticket_states: { available: 3 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 25.96,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 25.2,
      ticket_costs: [null, null, null],
      ticket_purchase_order_ids: [null, null, null],
      freshness: '< 30 mins',
      signature:
        'ZXcxY3d6c2FzMFg1QTNFcWJIeDFUZEpMSlc3dm12RDRjemo0L2F2Z3JVZz0tLVVmOHBlSUdGVnhaL2Z5SUJCcmRXQ3c9PQ==--ed10ac352469aae25517c02bafd7ca16f2bb14fd',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 453609584,
      url: '/ticket_groups/453609584',
      type: 'event',
      row: '1',
      section: '301',
      quantity: 3,
      available_quantity: 3,
      section_id: 119462,
      ticket_type: 'cheap',
      wholesale_price: 26.25,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: 'MOBILE TICKETS - MOBILE QR',
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-03-20T16:00:15Z',
      updated_at: '2018-04-09T13:37:47Z',
      splits: [1, 3],
      ticket_states: { available: 3 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 26.25,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 25.49,
      ticket_costs: [null, null, null],
      ticket_purchase_order_ids: [null, null, null],
      freshness: '< 30 mins',
      signature:
        'UXcrWEthYTljTi9ERmM5UFdoankycG8ya3FqajcwVnlSak9oZlpBV1lxMD0tLVV0c3NmS2IwU0dUSmNUc2F3WGRZNkE9PQ==--04b8f48bf9b206a7709f28385f3f250413181bb7',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 436049045,
      url: '/ticket_groups/436049045',
      type: 'event',
      row: '32',
      section: '107',
      quantity: 2,
      available_quantity: 2,
      section_id: 119390,
      ticket_type: 'expensive',
      wholesale_price: 27.04,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-01-16T21:27:49Z',
      updated_at: '2018-04-06T15:57:43Z',
      splits: [2],
      ticket_states: { available: 2 },
      ticket_hold_ids: ['NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 27.04,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 26.25,
      ticket_costs: [null, null],
      ticket_purchase_order_ids: [null, null],
      freshness: '< 30 mins',
      signature:
        'UXB4OTFLM0xpckxZTGZmdlpkQ1pQbHlkSDUxSEhJTWxzT2V3WTNmUVpKRT0tLVRsTWtYQ0JkWFQrYnpnSHVya2dCblE9PQ==--b57d0d177049d3e300df6a6ab2918493c55b39a5',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 432444819,
      url: '/ticket_groups/432444819',
      type: 'event',
      row: '2',
      section: '301',
      quantity: 2,
      available_quantity: 2,
      section_id: 119462,
      ticket_type: 'cheap',
      wholesale_price: 27.04,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2017-12-28T16:57:35Z',
      updated_at: '2018-04-06T15:57:41Z',
      splits: [2],
      ticket_states: { available: 2 },
      ticket_hold_ids: ['NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 27.04,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 26.25,
      ticket_costs: [null, null],
      ticket_purchase_order_ids: [null, null],
      freshness: '< 30 mins',
      signature:
        'dGVXUWhvWlk5aVVPQmc0NWFrU3dzU1lDNjQrRlFTb2VldFZPT3RLbi9UYz0tLVo0UlV0R2l0OTJ2Y0I5M2JTY0pESnc9PQ==--29b9bfc44cda529dfbce080562b4f817029bd6b2',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 457640236,
      url: '/ticket_groups/457640236',
      type: 'event',
      row: '14',
      section: '141',
      quantity: 2,
      available_quantity: 2,
      section_id: 119379,
      ticket_type: 'primary',
      wholesale_price: 28.12,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-04-09T15:21:19Z',
      updated_at: '2018-04-09T15:21:20Z',
      splits: [2],
      ticket_states: { available: 2 },
      ticket_hold_ids: ['NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 28.12,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 27.3,
      ticket_costs: [null, null],
      ticket_purchase_order_ids: [null, null],
      freshness: '< 30 mins',
      signature:
        'UG1HR2RybDlhanJLT2FScXpIVmtUZzV6aTNIdnlnempqSEdKRUpkN04wRT0tLXFORXV1U2Y4QnRFOHN0UzlON2xMZXc9PQ==--cd7fe182a756a35b0b824d59fc6a829b751987ad',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 432444821,
      url: '/ticket_groups/432444821',
      type: 'event',
      row: '1',
      section: '301',
      quantity: 2,
      available_quantity: 2,
      section_id: 119462,
      ticket_type: 'expensive',
      wholesale_price: 28.12,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2017-12-28T16:57:35Z',
      updated_at: '2018-04-09T13:45:04Z',
      splits: [2],
      ticket_states: { available: 2 },
      ticket_hold_ids: ['NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 28.12,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 27.3,
      ticket_costs: [null, null],
      ticket_purchase_order_ids: [null, null],
      freshness: '< 30 mins',
      signature:
        'OFVoK05ZSHJxN3JiVExYUEhjWlBSZFhXMWtUeWhkMGVWbEl0YXJNNTh5UT0tLUMvcGlLQU5oOURwVDF2Um5FYXd4TFE9PQ==--26732e57c243a539962513ee5bf1e5747477cceb',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 432444818,
      url: '/ticket_groups/432444818',
      type: 'event',
      row: '13',
      section: '317',
      quantity: 4,
      available_quantity: 4,
      section_id: 119454,
      ticket_type: 'expensive',
      wholesale_price: 28.12,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: true,
      in_hand_on: null,
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2017-12-28T16:57:35Z',
      updated_at: '2018-04-09T15:20:33Z',
      splits: [2, 4],
      ticket_states: { available: 4 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 28.12,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 27.3,
      ticket_costs: [null, null, null, null],
      ticket_purchase_order_ids: [null, null, null, null],
      freshness: '< 30 mins',
      signature:
        'UVNma3pSMUx5OCtySHFIeEdveHMwSE9sK1JRcDZWSVdKdVowck5LQjR3ND0tLTUzWFJibG1sNXRMb3lNOUVvQVhOVFE9PQ==--34acda432dca0a9aaca0152145c43165ce8f45ee',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 456824847,
      url: '/ticket_groups/456824847',
      type: 'event',
      row: '10',
      section: '330',
      quantity: 7,
      available_quantity: 7,
      section_id: 119478,
      ticket_type: 'cheap',
      wholesale_price: 28.84,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: false,
      in_hand_on: '2018-04-20',
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-04-04T16:25:23Z',
      updated_at: '2018-04-08T01:51:57Z',
      splits: [1, 2, 3, 4, 5, 7],
      ticket_states: { available: 7 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL']
      ],
      has_spec_tickets: false,
      featured: false,
      retail_price: 28.84,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 28,
      ticket_costs: [null, null, null, null, null, null, null],
      ticket_purchase_order_ids: [null, null, null, null, null, null, null],
      freshness: '< 30 mins',
      signature:
        'Q1VsRTRBSjFja09nYzk5SXJhQjJsbCsxMU5LK0hlOGhUdkNjUksrd2Z1Yz0tLWFzMWdPVXRGUFpkcjVQK0M0WHBGdXc9PQ==--e7676df0a3a6658493afcc70993be789e5154056',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 456824858,
      url: '/ticket_groups/456824858',
      type: 'event',
      row: '13',
      section: '329',
      quantity: 5,
      available_quantity: 5,
      section_id: 119477,
      ticket_type: 'primary',
      wholesale_price: 28.84,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: false,
      in_hand_on: '2018-04-20',
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-04-04T16:25:23Z',
      updated_at: '2018-04-09T12:23:00Z',
      splits: [1, 2, 3, 5],
      ticket_states: { available: 5 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL']
      ],
      has_spec_tickets: false,
      featured: false,
      retail_price: 28.84,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 28,
      ticket_costs: [null, null, null, null, null],
      ticket_purchase_order_ids: [null, null, null, null, null],
      freshness: '< 30 mins',
      signature:
        'enFwQWwzZk4vZTlWL3MyMG1tMmMyc1NDQkJZdldlU21VSGxCbkZLYWhTND0tLVV4MzJsQVgrTm81N2pGMVg4YnYxd2c9PQ==--a6d70e7a3bcee8ddb7abc5fee39b826bce85b3f8',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 456824911,
      url: '/ticket_groups/456824911',
      type: 'event',
      row: '6',
      section: '302',
      quantity: 4,
      available_quantity: 4,
      section_id: 119463,
      ticket_type: 'primary',
      wholesale_price: 28.84,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: false,
      in_hand_on: '2018-04-20',
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-04-04T16:25:25Z',
      updated_at: '2018-04-08T05:09:32Z',
      splits: [2, 4],
      ticket_states: { available: 4 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL'], ['available', 'NULL']],
      has_spec_tickets: false,
      featured: false,
      retail_price: 28.84,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 28,
      ticket_costs: [null, null, null, null],
      ticket_purchase_order_ids: [null, null, null, null],
      freshness: '< 30 mins',
      signature:
        'NkdhQTVIR0FiTnk0T2JVYWphY2NlTGxjbldSWVQ1N25OdmhGdWkycE0rYz0tLUU3eExkdWlJaEZQSVAxN2s4bnlvWkE9PQ==--9cb9993c543dbc93c86350c815790f7f089cd009',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    },
    {
      id: 456824852,
      url: '/ticket_groups/456824852',
      type: 'event',
      row: '10',
      section: '331',
      quantity: 8,
      available_quantity: 8,
      section_id: 119479,
      ticket_type: 'cheap',
      wholesale_price: 28.84,
      eticket: true,
      instant_delivery: false,
      intended_for_instant_delivery: false,
      in_hand: false,
      in_hand_on: '2018-04-20',
      remote_id: null,
      public_notes: null,
      private_notes: null,
      exchange_notes: null,
      created_at: '2018-04-04T16:25:23Z',
      updated_at: '2018-04-08T01:51:57Z',
      splits: [1, 2, 3, 4, 5, 6, 8],
      ticket_states: { available: 8 },
      ticket_hold_ids: ['NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL'],
      seats: [],
      tickets: [
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL'],
        ['available', 'NULL']
      ],
      has_spec_tickets: false,
      featured: false,
      retail_price: 28.84,
      format: 'Eticket',
      face_value: null,
      view_type: null,
      broadcast: 't',
      wheelchair: false,
      evopay_discount: 0,
      evopay_discount_price: 28,
      ticket_costs: [null, null, null, null, null, null, null, null],
      ticket_purchase_order_ids: [null, null, null, null, null, null, null, null],
      freshness: '< 30 mins',
      signature:
        'a2c3WS9zaktxQVl0OUJkdytmMzJKUHpKMCtwdlU4cjBtNzRaU2NHVUxscz0tLVpGRUJIbkZpbWxpM0xJTjc2N1NZY1E9PQ==--e076d0bfb46e24bbd3ce045857140ca812608376',
      event: {
        id: 1294624,
        url: '/events/1294624',
        name: 'San Diego Padres at Arizona Diamondbacks',
        occurs_at: '2018-04-21T17:10:00Z'
      },
      office: {
        id: 1692,
        url: '/offices/1692',
        name: 'Auto-Purchase',
        brokerage: { id: 1700, url: '/brokerages/1700', name: 'Auto-Purchase', abbreviation: 'TEvo Seller' }
      },
      natb_member: false
    }
  ]
}
